name: trim
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - biopython=1.85=py39hb25bd0a_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - contourpy=1.2.0=py39hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h5bd4931_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py39hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.84.2=h6a678d5_0
  - glib-tools=2.84.2=h6a678d5_0
  - glm=0.9.9.4=hc9558a2_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - importlib_resources=6.5.2=py39h06a4308_0
  - jpeg=9e=h166bdaf_1
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.1.1=h0131e85_1
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libcblas=3.9.0=37_h0358290_openblas
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=h252cb56_2
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.84.2=h37c7471_0
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=37_h47877c9_openblas
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.30=h46f56fc_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=h02b6914_2
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.29=h166bdaf_1
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.8.4=py39h06a4308_0
  - matplotlib-base=3.8.4=py39h1128e8f_0
  - mysql=8.4.0=h721767e_2
  - ncurses=6.5=h7934f7d_0
  - numpy=1.22.3=py39hc58783e_2
  - openbabel=3.1.1=py39hee2736e_3
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=pyh29332c3_1
  - pandas=1.4.2=py39h1832856_1
  - pcre2=10.42=hebb0a14_1
  - pillow=11.3.0=py39hb1c3d2d_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycirclize=1.9.1=pyhd8ed1ab_0
  - pymol-open-source=2.4.0=py39h20a8f2e_3
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.4=py39h5a03fae_0
  - pyqt5-sip=12.9.0=py39h5a03fae_0
  - python=3.9.24=h602e5db_0
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python_abi=3.9=2_cp39
  - pytz=2025.2=py39h06a4308_0
  - qt-main=5.15.2=hb6262e9_12
  - readline=8.3=hc2a1206_0
  - seaborn=0.13.2=py39h06a4308_3
  - setuptools=80.9.0=py39h06a4308_0
  - sip=6.5.1=py39he80948d_2
  - six=1.17.0=py39h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - toml=0.10.2=pyhd8ed1ab_1
  - tornado=6.5.1=py39h5eee18b_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zipp=3.21.0=py39h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.2=h8a70e8d_1
  - pip:
      - lxml==6.0.2
      - plip==2.4.0
prefix: /public/envs/hzclab/envs/plip
